routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\RoomBillController;
use App\Http\Controllers\RoomCategoriesController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomStatusController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/denies', [App\Http\Controllers\HomeController::class, 'denies'])->name('denies');

/*------ Client ------*/
Route::prefix('client')->name('client.')->group(function () {

    $class = ClientController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/about-us', [$class, 'aboutUs'])->name('about-us');
    Route::get('/contacts', [$class, 'contacts'])->name('contacts');
    Route::get('/typography', [$class, 'typography'])->name('typography');
    Route::get('/reservation', [$class, 'reservation'])->name('reservation');
    Route::get('/rooms', [$class, 'rooms'])->name('rooms');
    Route::get('/selectRoom', [$class, 'selectRoom'])->name('selectRoom');
    Route::post('/', [RoomBillController::class, 'book'])->name('book');
});

Route::get('/index', [StatusController::class, 'index'])->name('listStatus');
Route::get('/search', [StatusController::class, 'search'])->name('search');
// Route::get('/searchStatus/{array}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/showDetail/{category_name}/{room_name}/{double_bed}/{single_bed}/{price}/{description}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/order/{category_name}/{room_name}/{price}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'order'])->name('order');
// Route::post('/reservation/{client_name}/{phone}/{email}/{ID_Card}/{category_name}/{room_name}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}/{price}/{payment}', [StatusController::class, 'reservation'])->name('reservation');
Route::post('/reservation', [StatusController::class, 'reservation'])->name('reservation');
Route::get('/{reservation}/editReservation', [ReservationController::class, 'edit'])->name('editReservation');
Route::put('/{reservation}/updateReservation', [ReservationController::class, 'update'])->name('updateReservation');
Route::get('/chart/{room_name}', [StatusController::class, 'chart'])->name('chart');
Route::get('/searchReservation', [ReservationController::class, 'searchReservation'])->name('searchReservation');
Route::get('/viewDetailReservation/{id}', [ReservationController::class, 'viewDetail'])->name('viewDetail');
Route::get('/showReservation/{reservation}', [ReservationController::class, 'show'])->name('showReservation');
Route::get('/listAllReservation', [ReservationController::class, 'index'])->name('listAllReservation');
Route::get('/searchReservationByCode', [ReservationController::class, 'searchReservationByCode'])->name('searchReservationByCode');
Route::get('/createReservation', [ReservationController::class, 'create'])->name('createReservation');

Route::get('/s', [StatusController::class, 'listCategories'])->name('listCategories');

//new UI
Route::get('/listReservation', [ReservationController::class, 'index'])->name('listAllReservation');

//email
Route::get('/send_email', [MailController::class, 'sendEmail'])->name('sendEmail');

//sms
Route::get('/send_sms', [NotificationController::class, 'sendSms'])->name('sendSms');

//SMS twilio
Route::get('/sms', [NotificationController::class, 'sms'])->name('sms');

//test random
Route::get('/random', [NotificationController::class, 'randomCode'])->name('randomCode');

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->group(function () {

    /*------ Route Users ------*/
    Route::prefix('users')->name('users.')->group(function () {
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{user}', [$class, 'show'])->name('show');
        Route::put('/{user}', [$class, 'update'])->name('update');
        Route::delete('/{user}', [$class, 'destroy'])->name('destroy');
        Route::get('/{user}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route RoomCategory ------*/
    Route::prefix('categories')->name('categories.')->group(function () {
        $class = RoomCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomCategories}', [$class, 'show'])->name('show');
        Route::put('/{roomCategories}', [$class, 'update'])->name('update');
        Route::delete('/{roomCategories}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomCategories}/edit', [$class, 'edit'])->name('edit');
        Route::get('/{roomCategories}/select', [$class, 'SelectCategoryOrder'])->name('select');
    });

    /*------ Route Room ------*/
    Route::prefix('rooms')->name('rooms.')->group(function () {
        $class = RoomController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{room}', [$class, 'show'])->name('show');
        Route::put('/{room}', [$class, 'update'])->name('update');
        Route::delete('/{room}', [$class, 'destroy'])->name('destroy');
        Route::get('/{room}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's status ------*/
    Route::prefix('status')->name('status.')->group(function () {
        $class = RoomStatusController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomStatus}', [$class, 'show'])->name('show');
        Route::put('/{roomStatus}', [$class, 'update'])->name('update');
        Route::delete('/{roomStatus}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomStatus}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's order ------*/
    Route::prefix('bills')->name('bills.')->group(function () {
        $class = RoomBillController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomBill}', [$class, 'show'])->name('show');
        Route::put('/{roomBill}', [$class, 'update'])->name('update');
        Route::delete('/{roomBill}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomBill}/edit', [$class, 'edit'])->name('edit');
    });
});

app/Models/RoomBill.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class RoomBill extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'date_start',
        'date_finish',
        'client_name',
        'ID_Card',
        'phone',
        'email',
        'payment',
        'bill_status',
        'created_at',
        'updated_at'
    ];

    public function categories()
    {
        return $this->belongsTo(RoomCategories::class, 'category_id');
    }

    public function saveBill(Request $data)
    {
        $bill = $this->create([
            'category_id' => $data['category_id'],
            'client_name' => $data['client_name'],
            'date_start' => Carbon::parse($data['date_start'])->format('Y-m-d'),
            'date_finish' => Carbon::parse($data['date_finish'])->format('Y-m-d'),
            // 'date_start' => $data['date_start'],
            // 'date_finish' => $data['date_finish'],
            'ID_Card' => $data['ID_Card'],
            'phone' => $data['phone'],
            'email' => $data['email'],
            'payment' => $data['payment'],
            'bill_status' => 0,
        ]);

        return $bill;
    }

    public function search(array $data)
    {
        $filterStatus = array_key_exists('filter_status', $data) ? $data['filter_status'] : null;
        $phone = array_key_exists('key', $data) ? $data['key'] : null;
        $date_start = array_key_exists('filter_date_start', $data) ? $data['filter_date_start'] : null;
        $date_finish = array_key_exists('filter_date_finish', $data) ? $data['filter_date_finish'] : null;

        return $this
            ->SearchStatus($filterStatus)
            ->SearchPhone($phone)
            ->SearchDateStart($date_start)
            ->SearchDateFinish($date_finish)
            ->latest('id')
            ->paginate(array_key_exists('number', $data) ? $data['number'] : 5);
    }

    public function scopeSearchStatus($query, $filterStatus)
    {
        return $query->where('bill_status', 'like', '%' . $filterStatus . '%');
    }

    public function scopeSearchPhone($query, $phone)
    {
        return $query->where('phone', 'like', '%' . $phone . '%');
    }

    public function scopeSearchDateStart($query, $date_start)
    {
        return $query->where('date_start', 'like', '%' . $date_start . '%');
    }

    public function scopeSearchDateFinish($query, $date_finish)
    {
        return $query->where('date_finish', 'like', '%' . $date_finish . '%');
    }
}

app/Http/Controllers/RoomBillController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoomBillRequest;
use App\Http\Requests\UpdateRoomBillRequest;
use App\Models\RoomBill;
use App\Models\RoomCategories;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class RoomBillController extends Controller
{
    protected $bills;

    public function __construct(RoomBill $bills)
    {
        $this->bills = $bills;
        //$this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $bills = $this->bills->search($request->all());
        $roomCategories = RoomCategories::all();
        return view('AdminPage.room_bills.index', compact('bills', 'roomCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bills = RoomBill::all();
        $roomCategories = RoomCategories::all();
        return view('AdminPage.room_bills.create', compact('bills', 'roomCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoomBillRequest $request)
    {
        $this->bills->saveBill($request);
        return view("AdminPage.room_bills.success");
    }

    public function book(CreateRoomBillRequest $request)
    {
        $this->bills->saveBill($request);
        return Redirect::back()->with('success', 'The reservation is successful ! Please wait for the receptionist to contact you to confirm !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\RoomBill  $roomBill
     * @return \Illuminate\Http\Response
     */
    public function show(RoomBill $roomBill)
    {
        return view("AdminPage.room_bills.show", compact('roomBill'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\RoomBill  $roomBill
     * @return \Illuminate\Http\Response
     */
    public function edit(RoomBill $roomBill)
    {
        return view("AdminPage.room_bills.edit", compact('roomBill'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\RoomBill  $roomBill
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoomBillRequest $request, RoomBill $roomBill)
    {
        $roomBill->bill_status = $request->bill_status;
        $roomBill->payment = $request->payment;
        $roomBill->date_start = Carbon::parse($request->date_start)->format('Y-m-d');
        $roomBill->date_finish = Carbon::parse($request->date_finish)->format('Y-m-d');
        $roomBill->save();

        return redirect()->route('bills.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\RoomBill  $roomBill
     * @return \Illuminate\Http\Response
     */
    public function destroy(RoomBill $roomBill)
    {
        $roomBill->delete();
        return redirect()->route('bills.index');
    }
}

resources/views/AdminPage/room_bills/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h1 class="mt-4">Room Order</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Welcome to Room Order !!</li>
                </ol>
                <div class="card">
                    <div class="card-header">{{ __('Order') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('bills.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label for="role" class="col-md-4 col-form-label text-md-right">Select Room Category</label>
                                <div class="col-md-6">
                                    <select name="category_id" class="form-select form-select-sm">
                                        @foreach ($roomCategories as $category)
                                            <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Date Start*
                                    (dd-mm-YYYY)</label>
                                <div class="col-md-6">
                                    <input id="date_start" value="{{ old('date_start') }}" name="date_start" type="date"
                                        class="form-control @error('date_start') is-invalid @enderror">
                                    @error('date_start')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Date Finish*
                                    (dd-mm-YYYY)</label>
                                <div class="col-md-6">
                                    <input id="date_finish" value="{{ old('date_finish') }}" name="date_finish"
                                        type="date" class="form-control @error('date_finish') is-invalid @enderror">
                                    @error('date_finish')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Name*</label>
                                <div class="col-md-6">
                                    <input id="client_name" value="{{ old('client_name') }}" name="client_name"
                                        type="text" class="form-control @error('client_name') is-invalid @enderror">
                                    @error('client_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">ID_Card*</label>
                                <div class="col-md-6">
                                    <input id="ID_Card" value="{{ old('ID_Card') }}" name="ID_Card" type="text"
                                        class="form-control @error('ID_Card') is-invalid @enderror">
                                    @error('ID_Card')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Phone number*</label>
                                <div class="col-md-6">
                                    <input id="phone" value="{{ old('phone') }}" name="phone" type="text"
                                        class="form-control @error('phone') is-invalid @enderror">
                                    @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>
                                <div class="col-md-6">
                                    <input id="email" value="{{ old('email') }}" name="email" type="text"
                                        class="form-control @error('email') is-invalid @enderror">
                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <br>
                            <div class="form-group row">
                                <label for="role" class="col-md-4 col-form-label text-md-right">Payment method</label>
                                <div class="col-md-6">
                                    <div class="form-check">
                                        <input type="radio" name="payment" value="0" checked>
                                        <label for="">Cash</label>
                                    </div>
                                    <div class="form-check">
                                        <input type="radio" name="payment" value="1">
                                        <label for="">Bank Card</label>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Order
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/AdminPage/room_bills/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-12">
                <h1 class="mt-4">Room Orders Management</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Welcome to Room Orders Management !!</li>
                </ol>
                <div class="card">
                    <form action="{{ route('bills.index') }}" method="GET" class="md-3 d-flex">

                        <select name="filter_status">
                            <option value="">Filter by Status</option>
                            <option name="bill_status" value="0" {{ request('filter_status') == '0' ? 'selected' : '' }}>
                                Unconfirmed</option>
                            <option name="bill_status" value="1" {{ request('filter_status') == '1' ? 'selected' : '' }}>
                                Confirmed</option>
                            <option name="bill_status" value="2" {{ request('filter_status') == '2' ? 'selected' : '' }}>
                                Paid</option>
                            <option name="bill_status" value="3" {{ request('filter_status') == '3' ? 'selected' : '' }}>
                                Cancelled</option>
                        </select>

                        <input type="text" class="form-control" placeholder="Enter phonenumber..." name="key"
                            value="{{ request('key') }}">
                        <input type="date" class="form-control" placeholder="Enter date start..." name="filter_date_start"
                            value="{{ request('date_start') }}">
                        <input type="date" class="form-control" placeholder="Enter date finish..."
                            name="filter_date_finish" value="{{ request('date_end') }}">
                        <input type="text" class="form-control" placeholder="Enter number per page" name="number"
                            value="{{ request('number') }}">

                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>
                    <div class="card-body">

                        <table class="table">

                            <thead>
                                <tr>
                                    {{-- <th scope="col">ID</th> --}}
                                    <th scope="col">Category</th>
                                    <th scope="col">Check-in</th>
                                    <th scope="col">Check-out</th>
                                    <th scope="col">Client's name</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Payment</th>
                                    <th scope="col">Time order</th>
                                    <th scope="col">Status</th>
                                    @receptionist
                                    <th scope="col">Actions</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($bills as $bill)
                                    <tr>
                                        {{-- <th scope="row">{{ $bill->id }}</th> --}}
                                        <td>
                                            @foreach ($roomCategories as $category)
                                                @if ($bill->category_id == $category->id)
                                                    {{ $category->category_name }}
                                                @endif
                                            @endforeach
                                        </td>
                                        <td>{{ $bill->date_start }}</td>
                                        <td>{{ $bill->date_finish }}</td>
                                        <td>{{ $bill->client_name }}</td>
                                        <td>{{ $bill->phone }}</td>
                                        <td>{{ $bill->email }}</td>
                                        <td>
                                            @if ($bill->payment == '0') Cash
                                            @else
                                                Bank Card
                                            @endif
                                        </td>
                                        <td>{{ $bill->created_at }}</td>
                                        <td>
                                            @if ($bill->bill_status == '0') Unconfirmed
                                            @elseif($bill->bill_status == '1')
                                                Confirmed
                                            @elseif($bill->bill_status == '2')
                                                Paid
                                            @else
                                                Cancelled
                                            @endif
                                        </td>
                                        @receptionist
                                        <td>
                                            {{-- <a href="{{ route('bills.show', $bill->id) }}"><button type="button" class="btn btn-success">DETAIL</button></a> --}}
                                            <a href="{{ route('bills.edit', $bill->id) }}"><button type="button"
                                                    class="btn btn-warning">EDIT</button>
                                                <form action="{{ route('bills.destroy', $bill) }}" method="POST"
                                                    class="float-left">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger">DELETE</button>
                                                </form>
                                        </td>
                                @endif
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $bills->appends(request()->only('key', 'number', 'filter_status', 'phone', 'date_start', 'date_finish'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/AdminPage/room_bills/success.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Success</div>

                <div class="card-body">
                    The reservation is successful ! Please wait for the receptionist to contact you to confirm !
                </div>
            </div>
        </div>
    </div>
</div>
@endsection