routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\RoomBillController;
use App\Http\Controllers\RoomCategoriesController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomStatusController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/denies', [App\Http\Controllers\HomeController::class, 'denies'])->name('denies');

/*------ Client ------*/
Route::prefix('client')->name('client.')->group(function () {

    $class = ClientController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/about-us', [$class, 'aboutUs'])->name('about-us');
    Route::get('/contacts', [$class, 'contacts'])->name('contacts');
    Route::get('/typography', [$class, 'typography'])->name('typography');
    Route::get('/reservation', [$class, 'reservation'])->name('reservation');
    Route::get('/rooms', [$class, 'rooms'])->name('rooms');
    Route::get('/selectRoom', [$class, 'selectRoom'])->name('selectRoom');
    Route::post('/', [RoomBillController::class, 'book'])->name('book');
});

Route::get('/index', [StatusController::class, 'index'])->name('listStatus');
Route::get('/search', [StatusController::class, 'search'])->name('search');
// Route::get('/searchStatus/{array}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/showDetail/{category_name}/{room_name}/{double_bed}/{single_bed}/{price}/{description}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/order/{category_name}/{room_name}/{price}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'order'])->name('order');
// Route::post('/reservation/{client_name}/{phone}/{email}/{ID_Card}/{category_name}/{room_name}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}/{price}/{payment}', [StatusController::class, 'reservation'])->name('reservation');
Route::post('/reservation', [StatusController::class, 'reservation'])->name('reservation');
Route::get('/{reservation}/editReservation', [ReservationController::class, 'edit'])->name('editReservation');
Route::put('/{reservation}/updateReservation', [ReservationController::class, 'update'])->name('updateReservation');
Route::get('/chart/{room_name}', [StatusController::class, 'chart'])->name('chart');
Route::get('/searchReservation', [ReservationController::class, 'searchReservation'])->name('searchReservation');
Route::get('/viewDetailReservation/{id}', [ReservationController::class, 'viewDetail'])->name('viewDetail');
Route::get('/showReservation/{reservation}', [ReservationController::class, 'show'])->name('showReservation');
Route::get('/listAllReservation', [ReservationController::class, 'index'])->name('listAllReservation');
Route::get('/searchReservationByCode', [ReservationController::class, 'searchReservationByCode'])->name('searchReservationByCode');
Route::get('/createReservation', [ReservationController::class, 'create'])->name('createReservation');

Route::get('/s', [StatusController::class, 'listCategories'])->name('listCategories');

//new UI
Route::get('/listReservation', [ReservationController::class, 'index'])->name('listAllReservation');

//email
Route::get('/send_email', [MailController::class, 'sendEmail'])->name('sendEmail');

//sms
Route::get('/send_sms', [NotificationController::class, 'sendSms'])->name('sendSms');

//SMS twilio
Route::get('/sms', [NotificationController::class, 'sms'])->name('sms');

//test random
Route::get('/random', [NotificationController::class, 'randomCode'])->name('randomCode');

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->group(function () {

    /*------ Route Users ------*/
    Route::prefix('users')->name('users.')->group(function () {
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{user}', [$class, 'show'])->name('show');
        Route::put('/{user}', [$class, 'update'])->name('update');
        Route::delete('/{user}', [$class, 'destroy'])->name('destroy');
        Route::get('/{user}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route RoomCategory ------*/
    Route::prefix('categories')->name('categories.')->group(function () {
        $class = RoomCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomCategories}', [$class, 'show'])->name('show');
        Route::put('/{roomCategories}', [$class, 'update'])->name('update');
        Route::delete('/{roomCategories}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomCategories}/edit', [$class, 'edit'])->name('edit');
        Route::get('/{roomCategories}/select', [$class, 'SelectCategoryOrder'])->name('select');
    });

    /*------ Route Room ------*/
    Route::prefix('rooms')->name('rooms.')->group(function () {
        $class = RoomController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{room}', [$class, 'show'])->name('show');
        Route::put('/{room}', [$class, 'update'])->name('update');
        Route::delete('/{room}', [$class, 'destroy'])->name('destroy');
        Route::get('/{room}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's status ------*/
    Route::prefix('status')->name('status.')->group(function () {
        $class = RoomStatusController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomStatus}', [$class, 'show'])->name('show');
        Route::put('/{roomStatus}', [$class, 'update'])->name('update');
        Route::delete('/{roomStatus}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomStatus}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's order ------*/
    Route::prefix('bills')->name('bills.')->group(function () {
        $class = RoomBillController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomBill}', [$class, 'show'])->name('show');
        Route::put('/{roomBill}', [$class, 'update'])->name('update');
        Route::delete('/{roomBill}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomBill}/edit', [$class, 'edit'])->name('edit');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_user', 'user_id', 'role_id');
    }

    public function hasRole($roles){
        foreach($roles as $role)
        {
            if($this->roles->contains('name', $role))
            {
                return true;
            }
        }
        return false;
    }

    public function attachRoles(int $roleId)
    {
        return $this->roles()->attach($roleId);
    }

    public function detachRoles()
    {
        return $this->roles()->detach();
    }

    public function syncRoles($role)
    {
        return $this->roles()->sync($role);
    }

    public function getRolesID($roles) //return 1 array cac roles
    {
        $getRoles = [];
        foreach($roles as $role)
        {
            $getRoles[] = $role;
        }
        return $getRoles;
    }

    public function saveUser(Request $data)
    {
        $user = $this->create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);

        if(empty($data['roles']))
        {
            $roles = [
                'client' => '4'
            ];
        }
        else
        {
            $roles = $this->getRolesID($data['roles']);
        }

        $user->roles()->attach($roles);

        return $user;
    }


    public function search(array $data)
    {
        $userName = array_key_exists('key', $data) ? $data['key'] : null;
        $role_id = array_key_exists('filter_role', $data) ? $data['filter_role'] : null;

        return $this
                    ->WhereHasRoles($role_id)
                    ->SearchUserName($userName)
                    ->latest('id')
                    ->paginate(array_key_exists('number', $data) ? $data['number'] : 3);
    }

    public function scopeSearchUserName($query, $userName)
    {
        return $query->where('name', 'like', '%' . $userName . '%');
    }

    public function scopeWhereHasRoles($query, $role_id)
    {
        return $role_id ? $query->WhereHas('roles', function (Builder $query) use ($role_id) {
            $query->where('roles.id', $role_id);
        })
        : null;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use App\Rules\StrLengthRule;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    protected $users;

    public function __construct(User $users)
    {
        $this->users = $users;
        //$this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::all();
        $users = $this->users->search($request->all());
        return view('AdminPage.users.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('AdminPage.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(CreateUserRequest $request)
    {
        $this->users->saveUser($request);
        return redirect(route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $roles = Role::all();

        return view('AdminPage.users.show')->with([
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        return view("AdminPage.users.edit")->with([
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name' => [
                'required',
                'alpha',
                new StrLengthRule()
            ],
            'email' => ['required', 'string', 'email', 'max:255',
                Rule::unique('users')->ignore($user),
            ],
        ]);

        if(empty($request->roles))
        {
            $roles = [
                'client' => '4'
            ];
            $user->roles()->sync($roles);
        }
        else
        {
            $user->roles()->sync($request->roles);
        }

        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('users.index');
    }

}

resources/views/AdminPage/users/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Roles</label>
                            <div class="col-md-6">
                                @foreach ($roles as $role)
                                    <div class="form-check">
                                        <input type="checkbox" name="roles[{{$role->name}}]" value="{{ $role->id }}"
                                        @if($role->id == 4) checked @endif>
                                        <label for="">{{ $role->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/users/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Users {{$user->name}}</div>

                <div class="card-body">
                    <form action="{{ route('users.update', $user) }}" method="POST">

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">E-Mail</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="roles" class="col-md-4 col-form-label text-md-right">Roles</label>
                            <div class="col-md-6">
                                @foreach ($roles as $role)
                                    <div class="form-check">
                                        <input type="checkbox" name="roles[]" value="{{ $role->id }}"
                                            @if($user->roles->pluck('id')->contains($role->id)) checked @endif>
                                        <label for="">{{ $role->name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/users/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-12">
            <h1 class="mt-4">Users Management</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to Users Management !!</li>
            </ol>
            <div class="card">
                <div class="card-header">
                    @admin
                    <a href="{{ route('users.create') }}" class="btn btn-primary">Create New User</a>
                    @endif
                </div>

                <form action="{{ route("users.index") }}" method="GET" class="md-3 d-flex">
                    <select name="filter_role">
                        <option value="">Filter by Role</option>
                        @foreach ($roles as $role)
                            <option value="{{ $role->id }}" {{ request('filter_role') == $role->id ? "selected":"" }}> {{ $role->name }}</option>
                        @endforeach
                    </select>

                    <input type="text" class="form-control" placeholder="Enter Username..." name="key" value="{{ request('key') }}">
                    <input type="text" class="form-control" placeholder="Enter number per page" name="number" value="{{ request('number') }}">

                    <button type="submit" class="btn btn-success">Search</button>
                </form>

                {{-- <form action="{{ route('users.index') }}" method="GET" class="md-3 d-flex">
                    <input type="text" class="form-control" name="key" value="{{request('key')}}" placeholder="Enter Username...">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form> --}}
                <div class="card-body">

                    <table class="table">

                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Roles</th>
                            @admin
                            <th scope="col">Actions</th>
                            @endif
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                            <tr>
                                <th scope="row">{{$user->id}}</th>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td>
                                @admin
                                <td>
                                    <a href="{{ route('users.show', $user->id) }}"><button type="button" class="btn btn-success">DETAIL</button></a>
                                    <a href="{{ route('users.edit', $user->id) }}"><button type="button" class="btn btn-warning">EDIT</button>
                                    <form action="{{ route('users.destroy', $user) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                </td>
                                @endif
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{$users->appends(request()->only('key','number','filter_role'))->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/users/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">User {{$user->name}}</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Roles</th>
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{{$user->id}}</th>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td>
                              </tr>
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection