routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\RoomBillController;
use App\Http\Controllers\RoomCategoriesController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomStatusController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/denies', [App\Http\Controllers\HomeController::class, 'denies'])->name('denies');

/*------ Client ------*/
Route::prefix('client')->name('client.')->group(function () {

    $class = ClientController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/about-us', [$class, 'aboutUs'])->name('about-us');
    Route::get('/contacts', [$class, 'contacts'])->name('contacts');
    Route::get('/typography', [$class, 'typography'])->name('typography');
    Route::get('/reservation', [$class, 'reservation'])->name('reservation');
    Route::get('/rooms', [$class, 'rooms'])->name('rooms');
    Route::get('/selectRoom', [$class, 'selectRoom'])->name('selectRoom');
    Route::post('/', [RoomBillController::class, 'book'])->name('book');
});

Route::get('/index', [StatusController::class, 'index'])->name('listStatus');
Route::get('/search', [StatusController::class, 'search'])->name('search');
// Route::get('/searchStatus/{array}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/showDetail/{category_name}/{room_name}/{double_bed}/{single_bed}/{price}/{description}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/order/{category_name}/{room_name}/{price}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'order'])->name('order');
// Route::post('/reservation/{client_name}/{phone}/{email}/{ID_Card}/{category_name}/{room_name}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}/{price}/{payment}', [StatusController::class, 'reservation'])->name('reservation');
Route::post('/reservation', [StatusController::class, 'reservation'])->name('reservation');
Route::get('/{reservation}/editReservation', [ReservationController::class, 'edit'])->name('editReservation');
Route::put('/{reservation}/updateReservation', [ReservationController::class, 'update'])->name('updateReservation');
Route::get('/chart/{room_name}', [StatusController::class, 'chart'])->name('chart');
Route::get('/searchReservation', [ReservationController::class, 'searchReservation'])->name('searchReservation');
Route::get('/viewDetailReservation/{id}', [ReservationController::class, 'viewDetail'])->name('viewDetail');
Route::get('/showReservation/{reservation}', [ReservationController::class, 'show'])->name('showReservation');
Route::get('/listAllReservation', [ReservationController::class, 'index'])->name('listAllReservation');
Route::get('/searchReservationByCode', [ReservationController::class, 'searchReservationByCode'])->name('searchReservationByCode');
Route::get('/createReservation', [ReservationController::class, 'create'])->name('createReservation');

Route::get('/s', [StatusController::class, 'listCategories'])->name('listCategories');

//new UI
Route::get('/listReservation', [ReservationController::class, 'index'])->name('listAllReservation');

//email
Route::get('/send_email', [MailController::class, 'sendEmail'])->name('sendEmail');

//sms
Route::get('/send_sms', [NotificationController::class, 'sendSms'])->name('sendSms');

//SMS twilio
Route::get('/sms', [NotificationController::class, 'sms'])->name('sms');

//test random
Route::get('/random', [NotificationController::class, 'randomCode'])->name('randomCode');

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->group(function () {

    /*------ Route Users ------*/
    Route::prefix('users')->name('users.')->group(function () {
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{user}', [$class, 'show'])->name('show');
        Route::put('/{user}', [$class, 'update'])->name('update');
        Route::delete('/{user}', [$class, 'destroy'])->name('destroy');
        Route::get('/{user}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route RoomCategory ------*/
    Route::prefix('categories')->name('categories.')->group(function () {
        $class = RoomCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomCategories}', [$class, 'show'])->name('show');
        Route::put('/{roomCategories}', [$class, 'update'])->name('update');
        Route::delete('/{roomCategories}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomCategories}/edit', [$class, 'edit'])->name('edit');
        Route::get('/{roomCategories}/select', [$class, 'SelectCategoryOrder'])->name('select');
    });

    /*------ Route Room ------*/
    Route::prefix('rooms')->name('rooms.')->group(function () {
        $class = RoomController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{room}', [$class, 'show'])->name('show');
        Route::put('/{room}', [$class, 'update'])->name('update');
        Route::delete('/{room}', [$class, 'destroy'])->name('destroy');
        Route::get('/{room}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's status ------*/
    Route::prefix('status')->name('status.')->group(function () {
        $class = RoomStatusController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomStatus}', [$class, 'show'])->name('show');
        Route::put('/{roomStatus}', [$class, 'update'])->name('update');
        Route::delete('/{roomStatus}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomStatus}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's order ------*/
    Route::prefix('bills')->name('bills.')->group(function () {
        $class = RoomBillController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomBill}', [$class, 'show'])->name('show');
        Route::put('/{roomBill}', [$class, 'update'])->name('update');
        Route::delete('/{roomBill}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomBill}/edit', [$class, 'edit'])->name('edit');
    });
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Room extends Model
{
    use HasFactory;

    protected $fillable = [
        'room_name',
        'description',
        'category_id'
    ];

    public function status()
    {
        return $this->hasMany(RoomStatus::class);
    }

    public function categories()
    {
        return $this->belongsTo(RoomCategories::class, 'category_name');
    }

    public function saveRoom(Request $data)
    {
        $room = $this->create([
            'room_name' => $data['room_name'],
            'description' => $data['description'],
            'category_name' => $data['category_name'],
        ]);

        return $room;
    }

    public function search(array $data)
    {
        $roomName = array_key_exists('key', $data) ? $data['key'] : null;
        $category = array_key_exists('filter_category', $data) ? $data['filter_category'] : null;

        return $this
            ->SearchRoomName($roomName)
            ->WhereHasCategory($category)
            ->latest('id')
            ->paginate(array_key_exists('number', $data) ? $data['number'] : 5);
    }

    public function scopeSearchRoomName($query, $roomName)
    {
        return $query->where('room_name', 'like', '%' . $roomName . '%');
    }

    public function scopeWhereHasCategory($query, $category)
    {
        return $query->where('category_name', 'like', '%' . $category . '%');
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoomRequest;
use App\Http\Requests\UpdateRoomRequest;
use App\Models\Room;
use App\Models\RoomCategories;
use App\Models\RoomStatus;
use App\Rules\StrLengthRule;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class RoomController extends Controller
{
    protected $rooms;

    public function __construct(Room $rooms)
    {
        $this->rooms = $rooms;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $rooms = $this->rooms->search($request->all());
        $roomCategories = RoomCategories::all();
        return view('AdminPage.rooms.index', compact('rooms', 'roomCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rooms = Room::all();
        $roomCategories = RoomCategories::all();
        return view('AdminPage.rooms.create', compact('rooms', 'roomCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoomRequest $request)
    {
        $this->rooms->saveRoom($request);
        return redirect(route('rooms.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function show(Room $room)
    {
        return view('AdminPage.rooms.show')->with([
            'room' => $room,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        $roomCategories = RoomCategories::all();
        return view("AdminPage.rooms.edit")->with([
            'roomCategories' => $roomCategories,
            'room' => $room,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Room $room)
    {
        $this->validate($request, [
            'room_name' => [
                'required',
                'alpha_dash',
                Rule::unique('rooms')->ignore($room),
                new StrLengthRule()
            ],
            'description' => 'required|min:6|max:255',
        ]);

        $room->room_name = $request->room_name;
        $room->category_id = $request->category_id;
        $room->description = $request->description;
        $room->save();

        return redirect()->route('rooms.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function destroy(Room $room)
    {
        $room->delete();
        return redirect()->route('rooms.index');
    }
}

resources/views/AdminPage/rooms/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create New Room') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('rooms.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Room Name') }}</label>
                            <div class="col-md-6">
                                <input id="room_name" value="{{ old('room_name') }}" name="room_name" type="text" class="form-control @error('room_name') is-invalid @enderror" >
                                @error('room_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>
                            <div class="col-md-6">
                                <input id="description" value="{{ old('description') }}" name="description" type="text" class="form-control @error('description') is-invalid @enderror" >
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">{{ __('Room Category') }}</label>
                            <div class="col-md-6">
                                @foreach ($roomCategories as $category)
                                    <div class="form-check">
                                        <input type="radio" name="category_id" id="category_name" value="{{ $category->id }}"
                                        @if($category->id == 1) checked @endif>
                                        <label for="">{{ $category->category_name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/rooms/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Room {{$room->id}}</div>

                <div class="card-body">
                    <form action="{{ route('rooms.update', $room) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Room Name') }}</label>
                            <div class="col-md-6">
                                <input id="room_name" name="room_name" type="text" value="{{ $room->room_name }}" class="form-control @error('room_name') is-invalid @enderror" >
                                @error('room_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>
                            <div class="col-md-6">
                                <input id="description" name="description" type="text" value="{{ $room->description }}" class="form-control @error('description') is-invalid @enderror" >
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">{{ __('Room Category') }}</label>
                            <div class="col-md-6">
                                @foreach ($roomCategories as $category)
                                    <div class="form-check">
                                        <input type="radio" name="category_id" id="category_id" value="{{ $category->id }}"
                                        @if($room->category_id == $category->id) checked @endif>
                                        <label for="">{{ $category->category_name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/rooms/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-md-12">
                <h1 class="mt-4">Rooms Management</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Welcome to Rooms Management !!</li>
                </ol>
                <div class="card">
                    <div class="card-header">
                        @room_manager
                        <a href="{{ route('rooms.create') }}" class="btn btn-primary">Create New Rooms</a>
                        @endif
                    </div>
                    <form action="{{ route('rooms.index') }}" method="GET" class="md-3 d-flex">
                        <select name="filter_category">
                            <option value="">Filter by Category</option>
                            @foreach ($roomCategories as $category)
                                <option value="{{ $category->name }}"
                                    {{ request('filter_category') == $category->name ? 'selected' : '' }}>
                                    {{ $category->category_name }}</option>
                            @endforeach
                        </select>

                        <input type="text" class="form-control" placeholder="Enter room's name..." name="key"
                            value="{{ request('key') }}">
                        <input type="text" class="form-control" placeholder="Enter number per page" name="number"
                            value="{{ request('number') }}">

                        <button type="submit" class="btn btn-success">Search</button>
                    </form>


                    {{-- <form action="{{ route('rooms.index') }}" method="GET" class="md-3 d-flex">
                    <input type="text" class="form-control" name="key" value="{{request('key')}}">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form> --}}
                    <div class="card-body">

                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Name</th>
                                    {{-- <th scope="col">Description</th> --}}
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($rooms as $room)
                                    <tr>
                                        <th scope="row">{{ $room->id }}</th>
                                        <td>
                                            @foreach ($roomCategories as $category)
                                                @if ($room->category_name == $category->category_name)
                                                    {{ $category->category_name }}
                                                @endif
                                            @endforeach
                                        </td>
                                        <td>{{ $room->room_name }}</td>
                                        {{-- <td>{{ $room->description }}</td> --}}
                                        <td>
                                            <a href="{{ route('chart', $room->room_name) }}"><button type="button"
                                                    class="btn btn-primary">STATUS</button></a>
                                            @room_manager
                                            <a href="{{ route('rooms.show', $room->id) }}"><button type="button"
                                                    class="btn btn-success">DETAIL</button></a>
                                            <a href="{{ route('rooms.edit', $room->id) }}"><button type="button"
                                                    class="btn btn-warning">EDIT</button></a>
                                            <form action="{{ route('rooms.destroy', $room) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger">DELETE</button>
                                            </form>
                                @endif
                                </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $rooms->appends(request()->only('key', 'number', 'filter_category'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/AdminPage/rooms/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Room {{$room->id}}</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Category</th>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{{$room->id}}</th>
                                <td>{{$room->category_id}}</td>
                                <td>{{$room->room_name}}</td>
                                <td>{{$room->description}}</td>
                              </tr>
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection