routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\MailController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\RoomBillController;
use App\Http\Controllers\RoomCategoriesController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomStatusController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/denies', [App\Http\Controllers\HomeController::class, 'denies'])->name('denies');

/*------ Client ------*/
Route::prefix('client')->name('client.')->group(function () {

    $class = ClientController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/about-us', [$class, 'aboutUs'])->name('about-us');
    Route::get('/contacts', [$class, 'contacts'])->name('contacts');
    Route::get('/typography', [$class, 'typography'])->name('typography');
    Route::get('/reservation', [$class, 'reservation'])->name('reservation');
    Route::get('/rooms', [$class, 'rooms'])->name('rooms');
    Route::get('/selectRoom', [$class, 'selectRoom'])->name('selectRoom');
    Route::post('/', [RoomBillController::class, 'book'])->name('book');
});

Route::get('/index', [StatusController::class, 'index'])->name('listStatus');
Route::get('/search', [StatusController::class, 'search'])->name('search');
// Route::get('/searchStatus/{array}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/showDetail/{category_name}/{room_name}/{double_bed}/{single_bed}/{price}/{description}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'show'])->name('showDetail');
Route::get('/order/{category_name}/{room_name}/{price}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}', [StatusController::class, 'order'])->name('order');
// Route::post('/reservation/{client_name}/{phone}/{email}/{ID_Card}/{category_name}/{room_name}/{number_of_adults}/{number_of_children}/{checkin}/{checkout}/{price}/{payment}', [StatusController::class, 'reservation'])->name('reservation');
Route::post('/reservation', [StatusController::class, 'reservation'])->name('reservation');
Route::get('/{reservation}/editReservation', [ReservationController::class, 'edit'])->name('editReservation');
Route::put('/{reservation}/updateReservation', [ReservationController::class, 'update'])->name('updateReservation');
Route::get('/chart/{room_name}', [StatusController::class, 'chart'])->name('chart');
Route::get('/searchReservation', [ReservationController::class, 'searchReservation'])->name('searchReservation');
Route::get('/viewDetailReservation/{id}', [ReservationController::class, 'viewDetail'])->name('viewDetail');
Route::get('/showReservation/{reservation}', [ReservationController::class, 'show'])->name('showReservation');
Route::get('/listAllReservation', [ReservationController::class, 'index'])->name('listAllReservation');
Route::get('/searchReservationByCode', [ReservationController::class, 'searchReservationByCode'])->name('searchReservationByCode');
Route::get('/createReservation', [ReservationController::class, 'create'])->name('createReservation');

Route::get('/s', [StatusController::class, 'listCategories'])->name('listCategories');

//new UI
Route::get('/listReservation', [ReservationController::class, 'index'])->name('listAllReservation');

//email
Route::get('/send_email', [MailController::class, 'sendEmail'])->name('sendEmail');

//sms
Route::get('/send_sms', [NotificationController::class, 'sendSms'])->name('sendSms');

//SMS twilio
Route::get('/sms', [NotificationController::class, 'sms'])->name('sms');

//test random
Route::get('/random', [NotificationController::class, 'randomCode'])->name('randomCode');

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->group(function () {

    /*------ Route Users ------*/
    Route::prefix('users')->name('users.')->group(function () {
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{user}', [$class, 'show'])->name('show');
        Route::put('/{user}', [$class, 'update'])->name('update');
        Route::delete('/{user}', [$class, 'destroy'])->name('destroy');
        Route::get('/{user}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route RoomCategory ------*/
    Route::prefix('categories')->name('categories.')->group(function () {
        $class = RoomCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomCategories}', [$class, 'show'])->name('show');
        Route::put('/{roomCategories}', [$class, 'update'])->name('update');
        Route::delete('/{roomCategories}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomCategories}/edit', [$class, 'edit'])->name('edit');
        Route::get('/{roomCategories}/select', [$class, 'SelectCategoryOrder'])->name('select');
    });

    /*------ Route Room ------*/
    Route::prefix('rooms')->name('rooms.')->group(function () {
        $class = RoomController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{room}', [$class, 'show'])->name('show');
        Route::put('/{room}', [$class, 'update'])->name('update');
        Route::delete('/{room}', [$class, 'destroy'])->name('destroy');
        Route::get('/{room}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's status ------*/
    Route::prefix('status')->name('status.')->group(function () {
        $class = RoomStatusController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomStatus}', [$class, 'show'])->name('show');
        Route::put('/{roomStatus}', [$class, 'update'])->name('update');
        Route::delete('/{roomStatus}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomStatus}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's order ------*/
    Route::prefix('bills')->name('bills.')->group(function () {
        $class = RoomBillController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomBill}', [$class, 'show'])->name('show');
        Route::put('/{roomBill}', [$class, 'update'])->name('update');
        Route::delete('/{roomBill}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomBill}/edit', [$class, 'edit'])->name('edit');
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Paradise Hotel</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">

        <!-- Navbar Brand-->
        <div class="navbar-brand ps-3">Paradise Hotel</div>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                {{-- <input class="form-control" type="text" placeholder="Hello, {{ Auth::user()->name }}"
                    aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"></button> --}}
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <!-- Right Side Of Navbar -->
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <!-- Authentication Links -->
                    <li>
                        <a id="navbarDropdown" class="dropdown-item" href="#" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>
                    <li>
                        <hr class="dropdown-divider" />
                    </li>
                    <div class="dropdown-item">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
            </li>
        </ul>
        {{-- <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                        </li>
                    </ul> --}}
        </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="{{ route('home') }}">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Index
                        </a>
                        <div class="sb-sidenav-menu-heading">Modules</div>
                        @admin
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                            data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            {{-- <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div> --}}
                            <a href="{{ route('users.index') }}" class="nav-link collapsed">User Management</a>
                        </a>
                        @endif
                        {{-- <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div> --}}


                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                            data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <a href="{{ route('rooms.index') }}" class="nav-link collapsed">Rooms Management</a>
                        </a>

                        @room_manager
                        <a href="{{ route('categories.index') }}" class="nav-link collapsed" data-bs-toggle="collapse"
                            data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <a href="{{ route('categories.index') }}" class="nav-link collapsed">Room Categories</a>
                        </a>
                        @endif

                        {{-- @receptionist
                        <a href="{{ route('categories.index') }}" class="nav-link collapsed"
                            data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false"
                            aria-controls="collapseLayouts">
                            <a href="{{ route('status.index') }}" class="nav-link collapsed">Statuses Management</a>
                        </a>
                        @endif --}}

                        @receptionist
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                            data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            {{-- <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div> --}}
                            {{-- <a href="{{ route('bills.index') }}" class="nav-link collapsed">Orders Management</a> --}}
                            <a href="{{ route('listAllReservation') }}" class="nav-link collapsed">Reservations
                                Management</a>
                            {{-- <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div> --}}
                        </a>
                        @endif

                        {{-- @client
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                            data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            <a href="{{ route('bills.create') }}" class="nav-link collapsed">Room Order</a>
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        @endif --}}

                        {{-- <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                                </nav>
                            </div> --}}

                        {{-- <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="charts.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Charts
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Tables
                            </a> --}}
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    {{ Auth::user()->name }}
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @yield('content')
            </main>
            @include('layouts.footer')
            {{-- <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer> --}}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
    </script>
    <script src="js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="js/datatables-simple-demo.js"></script>
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header_client.blade.php
<!-- start header -->
<div class="header_bg">
    <div class="wrap">
        <div class="header">
            <div class="logo">
                <a href="index.html"><img src="{{ asset('images/client/logo.png') }}" alt=""></a>
            </div>
            <div class="h_right">
                <!--start menu -->
                <ul class="menu">
                    <li class="active"><a href="{{ route('client.index') }}">hotel</a></li>
                    <li><a href="{{ route('client.rooms') }}">rooms & suits</a></li>
                    <li><a href="{{ route('client.reservation') }}">reservation</a></li>
                    <li><a href="{{ route('client.activities') }}">activities</a></li>
                    <li><a href="{{ route('client.contact') }}">contact</a></li>
                    <form action="{{ route('searchReservation') }}">
                        <input type="text" name="input">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                    <div class="clear"></div>
                </ul>
                <!-- start profile_details -->
                <form class="style-1 drp_dwn">
                    <div class="row">
                        <div class="grid_3 columns">
                            <select class="custom-select" id="select-1">
                                <option selected="selected">EN</option>
                                <option>USA</option>
                                <option>AUS</option>
                                <option>UK</option>
                                <option>IND</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="clear"></div>
            <div class="top-nav">
                <nav class="clearfix">
                    <ul>
                        <li class="active"><a href="{{ route('client.index') }}">hotel</a></li>
                        <li><a href="{{ route('client.rooms') }}">rooms & suits</a></li>
                        <li><a href="{{ route('client.reservation') }}">reservation</a></li>
                        <li><a href="{{ route('client.activities') }}">activities</a></li>
                        <li><a href="{{ route('client.contact') }}">contact</a></li>
                    </ul>
                    <a href="#" id="pull">Menu</a>
                </nav>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/header_hotel.blade.php
<!-- Page Header-->
<header class="page-header" style="padding-bottom: 24px">
    <!-- RD Navbar-->
    <div class="rd-navbar-wrap">
        <nav class="rd-navbar rd-navbar-default-with-top-panel" data-layout="rd-navbar-fixed"
            data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fullwidth" data-md-device-layout="rd-navbar-fixed"
            data-lg-layout="rd-navbar-fullwidth" data-lg-device-layout="rd-navbar-fullwidth"
            data-md-stick-up-offset="90px" data-lg-stick-up-offset="150px" data-stick-up="true" data-sm-stick-up="true"
            data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-top-panel rd-navbar-collapse">
                <div class="rd-navbar-top-panel-inner">
                    <div class="left-side">
                        <div class="group">
                            <span class="text-italic">Follow Us:</span>
                            <ul class="list-inline">
                                <li>
                                    <a class="icon icon-sm icon-secondary-5 fa fa-instagram" href="#"></a>
                                </li>
                                <li>
                                    <a class="icon icon-sm icon-secondary-5 fa fa-facebook" href="#"></a>
                                </li>
                                <li>
                                    <a class="icon icon-sm icon-secondary-5 fa fa-twitter" href="#"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="center-side">
                        <!-- RD Navbar Brand-->
                        <div class="rd-navbar-brand fullwidth-brand">
                            {{-- <a class="brand-name" href="{{ route('listStatus') }}"><img src="images/logo-default-314x48.png" alt=""
                                    width="314" height="48" /></a> --}}
                            <a class="brand-name" href="{{ route('listStatus') }}"><img
                                    src="{{ asset('images/Logo.png') }}" alt="" width="314"
                                    height="48" /></a>
                        </div>
                    </div>
                    <div class="right-side">
                        <!-- Contact Info-->
                        <div class="contact-info">
                            <div class="unit unit-middle unit-horizontal unit-spacing-xs">
                                <div class="unit__left">
                                    <span class="icon icon-primary text-middle mdi mdi-phone"></span>
                                </div>
                                <div class="unit__body">
                                    <a class="text-middle" href="tel:#">+84 (96) 777–5035</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rd-navbar-inner">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel">
                    <!-- RD Navbar Toggle-->
                    <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap">
                        <span></span>
                    </button>
                    <!-- RD Navbar collapse toggle-->
                    <button class="rd-navbar-collapse-toggle" data-rd-navbar-toggle=".rd-navbar-collapse">
                        <span></span>
                    </button>
                    <!-- RD Navbar Brand-->
                    <div class="rd-navbar-brand mobile-brand">
                        {{-- <a class="brand-name" href="{{ route('listStatus') }}"><img src="images/logo-default-314x48.png" alt=""
                                width="314" height="48" /></a> --}}
                        <a class="brand-name" href="{{ route('listStatus') }}"><img
                                src="{{ asset('images/Logo.png') }}" alt="" width="314"
                                height="48" /></a>
                    </div>
                </div>
                <div class="rd-navbar-aside-right">
                    <div class="rd-navbar-nav-wrap">
                        <div class="rd-navbar-nav-scroll-holder">
                            <ul class="rd-navbar-nav">
                                <li class="active">
                                    <a href="{{ route('listStatus') }}">Home</a>
                                </li>
                                <li>
                                    <a href="{{ route('client.about-us') }}">About Us</a>
                                </li>
                                <li>
                                    <a href="{{ route('client.contacts') }}">Contacts</a>
                                </li>
                                {{-- <li>
                                    <a href="{{ route('client.typography') }}">Typography</a>
                                </li> --}}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>